### ISSUE TITLE
Typo: About me Content

### ISSUE THREAD

**Issue by liambrewster** [conermurphy/conermurphy.com#1]
Hello coner, 

just practicing my github abilities, so i tweeted earlier about your website being great and used in research for my own. I noticed a typo, so following Eddie's advice to collobrate first etc, thought id raise an issue about it to help

delete this after seeing , have a great day

so on the about me, see below:
![image](https://user-images.githubusercontent.com/31896214/153963948-ea591b0b-efbe-4fc7-9934-67e5ba684109.png)

**Comment by conermurphy** [comment]
Hey Liam,

Thanks for letting me know. 

I'll look into it and get it sorted.

Unless you fancy creating a PR for it. 😅

Thank you

Coner

**Comment by liambrewster** [comment]
ill give a PR a go , why not :) Thanks

**Comment by liambrewster** [comment]
not sure if I have done it right, but thanks for the opportunity to try 

PR is here:-> #2
